version: '3.8'

services:
  web:
    build: ./shorten_links_backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shorten_links_backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  front:
    build: ./shorten_links_frontend/
    ports:
      - '8080:8080'
    volumes:
      - ./shorten_links_frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    command: 'npm run serve' 

volumes:
  postgres_data: